name: Sonar Scan and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: |
          mvn clean package

      - name: Deploy to Tomcat
        uses: peaceiris/actions-tomcat@v2
        with:
          war: target/*.war
          url: http://localhost:8083
          username: ${{ secrets.TOMCAT_USERNAME }}
          password: ${{ secrets.TOMCAT_PASSWORD }}

      # Add additional steps as needed for deployment or post-processing
